[build]
  command = ""       # no ejecuta build
  publish = "."      # publica todo desde la raíz del repo

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
